---
title: 'Cielo: November 2009 News'
date: 2009-10-28 22:53:20 -04:00
categories:
- News
tags:
- Cielo
layout: post
status: publish
author:
  display_name: Admin
  login: admin
  email: brian@plexipr.com
  url: http://www.plexipr.com
author_login: admin
author_email: brian@plexipr.com
author_url: http://www.plexipr.com
wordpress_id: 1764
wordpress_url: http://www.plexipr.com/?p=1764
date_gmt: '2009-10-29 03:53:20 -0400'
---

<p style="text-align: left;"><strong>FOR IMMEDIATE RELEASE</strong></p>
<p style="text-align: center;"><strong><a href="http://www.cieloclub.com"><img class="size-full wp-image-1766 aligncenter" title="Cielo" src="http://www.plexipr.com/wp-content/uploads/2009/10/Cielo1.jpg" alt="Cielo" width="221" height="74" /></a></strong><strong></strong></p>
<p style="text-align: center;"><strong>Cielo : November 2009 News</strong></p>
<p style="text-align: left;">Seven years ago, <strong>Cielo</strong> was the first venue in all of North America to install a <strong>Funktion One </strong>sound system, and has since then served as the company’s main showcase venue. Daniel Agne of Sound Investment AV performed the original installation when the club opened and he has exclusively tuned and maintained the system over the years.</p>
<p><strong>Funktion One</strong> are continually advancing audio quality and wherever possible provide an upgrade path for existing products in the field ensuring that clients maintain state of the art. Cielo is the first of the Funktion One clubs worldwide to benefit from the recent upgrades to the technology, completed early in October by Tony Andrews of Funktion One. With this recent upgrade at Cielo, the Infrabass 218s were fitted with improved dampening material giving a smoother, fatter bass.  The AX88s and Resolution 2 monitors were fitted with a more advanced Funktion One designed 8" loudspeaker resulting in faster, crisper mid range and refining the blend between the 8" and the high frequency units. Overall, the transient ability of the system has been raised to a new level, further raising the bar for a quality clubbing experience.</p>
<p>On Thursday November 5th we kick off the month with not one but two legends of dance as <em>Dance.Here.Now.</em> presents a night not to be missed in the company of <strong>Danny Krivit</strong> &amp; <strong>Hex Hector</strong>. Danny has over 35-years of DJ history in New York dating back to the days of the Roxy and Paradise Garage, through to the Shelter, Body &amp; Soul and most recently his soulful classics 718 Sessions (check the acclaim album, ‘<span style="text-decoration: underline;"><strong>718 Sessions Compilation</strong></span>’, just released via Nervous Records for a typical slice). Hex meanwhile is no slouch when it comes to dance music. Scan the New Yorker’s discography, and the credits include a staggering list of iconic ladies of dance: Madonna, Aretha, Whitney, Mariah, Britney and J-Lo - are just a fraction of the divas to receive his Midas touch. His restyling of Lopez’s blockbuster "Waiting For Tonight" even earning him the coveted GRAMMY award. Now based in Florida, Hector returns to his hometown on a night that promises a touch of nostalgia, a lesson in the old school, and guarantee to make you dance with abandon.</p>
<p>From the early days of Giant Step, to today's <em>Turntables On The Hudson</em> parties, <strong>Nickodemus</strong> has been a key element in the NYC dance scene for over a decade. As a DJ and producer he explores the intersection of urban and world music with elements of everything from funk and dub to folk and hip-hop… and all with a message of peace, awareness and love for the dance. On Friday Friday 6th Turntables On The Hudson returns to Cielo with Nickodemus joined on the decks by Brooklyn’s eclectic house, broken-soul and afro-Latin head<strong> Chris Annibell</strong> for a truly mind-enveloping journey into the many facets of house.</p>
<p>We’re graced with a true superstar DJ on Thursday 12th as <em>Dance.Here.Now.</em> presents the one and only <strong>Carl Cox</strong>. The first person to be named number one DJ in the world on <em>DJ Magazine's Top 100</em> poll back in ’97, the hardest-working and perhaps most-travelled DJ on the circuit, has remained in the upper echelons of the chart ever since, thanks to his global fan-base. “<em>I’ve been doing this for over 20-years and we’re still involved in pushing the music forward,</em>” says the man himself who’s helped take techno to the next level via his groundbreaking In-Tec label. “<em>We’ve been through so many genres of music and we’re still involved and still enjoying it. It’s fantastic to still be able to prevail that sound.</em>” Carl also holds a unique record as being lucky enough to see in the millennium not once but twice: first on spinning at Bondi Beach in Australia, then hopping on a jet over the timeline to Honolulu, Hawaii, to play a second set at midnight! Legend.</p>
<p>On Friday 13th <em>Playtime</em> does away with superstition as Cielo’s <strong>Willie Graff</strong> is joined by Irish electronica don <strong>Chymera</strong>. With a plethora of acclaimed releases to his name on such groundbreaking labels as Urban Torque. NRK and Ovum, the tech-house producer relocated to Barcelona where he quickly became a master at playing sun-kissed Balearic beats and chill out sessions with equal critical recognition. His DJ and live schedule is also booming taking in dates as far afield as Russia, Japan, Europe and America. Incidentally if you’re reaching for a tenuous link to impress your friends, Willie Graff was actually born to American parents on the island of Ibiza. He’s also in the enviable position of enjoying the best of both worlds: Pacha, Ibiza during the summer months and Cielo the rest for the year.</p>
<p>Pioneering International DVJ, producer and Little Mountain Recordings label boss <strong>Sander Kleinenberg</strong> guest stars at <em>Dance.Here.Now.</em> on Tuesday 17th. On the heels of his impressive new mix compilation called ‘<span style="text-decoration: underline;"><strong>This Is Sander Kleinenberg 2</strong></span>’ on Ultra Records, this compilation truly displays how versatile Sander can be, drawing on a vast array of styles and using them in an innovative way to create his unparalleled sound. Each disc offers something slightly different and follows on brilliantly from his hugely popular first compilation in the series. Just recently wrapping up his hugely successful Pure Pacha Ibiza residency, Sander is in the studio working on his debut artist album due in early 2010. The album will feature a plethora of amazing new productions, which he has worked on with U.S. heavyweight Josh Gabriel. The first single from the album will be Sander’s remarkable new tune “This Is Our Night” which has already gained support from BBC Radio 1’s Pete Tong. Get a sneak preview on this special night and an exclusive meet &amp; greet with Sander beginning at 12 midnight. <em>This Is New York!</em></p>
<p><em>Cielo</em> &amp; <em>Blk|Market Membership</em> present <strong>Damian Lazarus</strong> on the Thursday 19th For several years Damian Lazarus has been delivering a fresh and unique sound best described as dirty and deep electro house – a rebel sound designed for lovers of late night madness, future dance floor classics and cutting edge new ideas. As A&amp;R of City Rockers, he is responsible for signing and releasing classics like Felix Da Housecat’s ‘Silver Screen’, Tiga’s ‘Sunglasses’ and ‘Fly With Me’ by Coloursound. Since then his Crosstown Rebels imprint has maintained his dynamic and cutting edge approach to all things dance, while his DJ sets are designed for good time party heads: his style combines the most upfront twisted music with the best in cutting edge underground electronic embellished with a touch of punk attitude, as highlighted on his recently released debut LP opus ‘<span style="text-decoration: underline;"><strong>Smoke The Monster Out</strong></span>’.</p>
<p>Holland house siblings Rogier and Gregor van Bueren carved a niche for themselves as <strong>Hardsoul</strong>, one of the most consistent and prolific house acts to emerge in the new millennium. In recent times Roog has stepped out into the solo spotlight as both a DJ and producer his unique style of undeniably funky house infused with tribal and electro overtones. One of the hardest working DJs in Europe is guest of <em>Paradizo</em> on Saturday 21st alongside <strong>Willie Graff</strong>.</p>
<p>If dark acid basslines, Latin percussion, deep-house grooves and piano instrumentals float your boat then <strong>Abe Duque</strong> is the man for you on Sunday 22nd. The <em>Biatch Corp</em> presents the Hollis, NY resident who for over a decade has been behind some of the most musical, melodic and enveloping twisted tribal house and dark funky beats this city has produced. His sets employ deep driving grooves, brisk tribal percussion, sexually charged basslines and provocative vocals. In other words it’s a tribal house fan’s dream: hot, steamy, sexy and created with the sole purpose of making you dance.</p>
<p>“<em>I did not realize what my dream job was until the first time I heard Larry Levan play at the Garage,</em>” says <strong>Junior Vasquez</strong>. “<em>He created the alter and took you on a journey that allowed you to escape for a few magical hours. I knew then what I wanted to do with my life... make music and play music. When I began to DJ it was because I wanted to connect to everyone. I wanted music to bring us together and allow us to share that light that exists in all of us. So I worked hard and built a career for myself that I could have never imagined.</em>” That career is now well into its third decade and on Thursday 26th <em>Dance.Here.Now.</em> presents a Thanksgiving night of Classics from Junior Vasquez and his varied and colorful box of timeless records. Essential.</p>
<p>November rounds off with the return of <em>Adult Section</em> on Friday 27th and DJs <strong>Citizen Kane</strong> &amp; <strong>Darshan Jesrani </strong>bringing their considerable skills back to Cielo to paint an aural landscape on the senses. Kane, a truly OG NYC brother, has been a seminal and iconic figure in contemporary dance music culture since his emergence in the mid-‘90s, he was also a former disco buyer for the infamous A1 Records, and has been digging and collecting since his early teens. Brooklyn’s Darshan Jesrani was one half of the uber cool Metro Area (along with Morgan Geist), that left an incredible mark on the dance landscape with its forward-thinking, freestyle recombination of influences, revolving around classic production styles and the songwriting focus of disco, new-wave and synth-pop.</p>
<p><strong>CIELO NOVEMBER 2009 DATES</strong></p>
<p style="text-align: left;"><a href="http://www.cieloclub.com"><img class="alignnone size-full wp-image-1765" title="Cielo: November News" src="http://www.plexipr.com/wp-content/uploads/2009/10/Cielo+Nov.jpg" alt="Cielo: November News" width="500" height="550" /></a></p>
<p><strong>ABOUT CIELO</strong><br />
Located at 18 Little West 12th Street, in the heart of New York City’s trendy Meat Packing District, is open nightly from 10:00pm-4:00am. Cielo is a beautifully designed 350-capacity club featuring a world-class, state-of-the-art digital Funktion One soundsystem. Since its opening in 2003, Cielo has become an internationally renowned dance music nightclub brand and has upheld its edict of world-class music, professional service and all-inclusive atmosphere.</p>
<p>Over the last 6 years, Cielo has continued to triumph and collect accolades including; Club Awards 2009 winner for Best Party – Dance.Here.Now.; Club World Awards 2008 winner for Best Club (Winner 2005 &amp; 2006) and Best Party - Dance.Here.Now.; Top 50 Nightclubs in the World- DJ Magazine 2006, 2007 &amp; 2008; Best Nightclub- Village Voice 2006; Best Deep House Club- New York Magazine 2006; Best Resident DJ Francois K- Club World Awards 2006 &amp; 2005; Best Venue USA- URB Magazine 2005; Best Interior Design- Club World Awards 2004; Best Club- Dancestar Awards USA 2004. For more info, please go to <a href="http://">www.cieloclub.com</a>.</p>
