---
title: House of Rob Celebration September 16, Celebrate the life of NYC Nightlife
  Icon  Legend Rob Fernandez
date: 2015-08-27 17:15:31 -04:00
categories:
- Uncategorized
- Releases
layout: post
status: publish
author:
  display_name: Admin
  login: admin
  email: brian@plexipr.com
  url: http://www.plexipr.com
author_login: admin
author_email: brian@plexipr.com
author_url: http://www.plexipr.com
wordpress_id: 6547
wordpress_url: http://ymlp.com/zOl1MB
date_gmt: '2015-08-27 22:15:31 -0400'
---

<p><html><br />
<head><br />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/></head><br />
<body>
<div><span style="font-size: 10pt;"><b><span style="font-family: arial, helvetica, sans-serif;">FOR IMMEDIATE RELEASE</span></b></span></div>
<div style="text-align: center;">&nbsp;</div>
<div style="text-align: center;">&nbsp;</div>
<div style="text-align: center;"><b><span style="font-size: 10pt;"><span style="font-size: 12pt;"><span style="font-family: arial, helvetica, sans-serif;"><img height="100" src="http://img.ymlp.com/plexipr_RPMLOGO_1.jpg" width="100" style="border: 0pt none;" />&nbsp; &nbsp; &nbsp;&nbsp;<img src="http://img.ymlp.com/plexipr_HORlogo_1.jpg" height="83" width="100" style="border: 0pt none;" /><br /></span></span></span></b></div>
<div style="text-align: center;">&nbsp;</div>
<div style="text-align: center;"><span style="font-size: 10pt;"><span style="font-size: 12pt;"><span style="font-family: arial, helvetica, sans-serif;"><span id="docs-internal-guid-abb042be-ffa2-4f61-b320-dca44ed7bf0c"></p>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt; text-align: center;" dir="ltr"><span id="docs-internal-guid-36c0b7aa-70a6-780d-8e64-7c0147b59a66"></p>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt; text-align: center;" dir="ltr"><span style="font-size: 18.6666666666667px; font-family: Arial; font-weight: 700; vertical-align: baseline; white-space: pre-wrap;">HOUSE OF ROB CELEBRATION</span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt; text-align: center;" dir="ltr"><span style="font-size: 18.6666666666667px; font-family: Arial; font-weight: 700; vertical-align: baseline; white-space: pre-wrap;"> Celebrating the life of NYC Nightlife Icon and Legend Rob Fernandez</span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt; text-align: center;" dir="ltr"><span style="font-size: 18.6666666666667px; font-family: Arial; font-weight: 700; vertical-align: baseline; white-space: pre-wrap;">September 16, 2015</span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt; text-align: center;" dir="ltr"><span style="font-size: 18.6666666666667px; font-family: Arial; font-weight: 700; vertical-align: baseline; white-space: pre-wrap;">Pacha NYC</span></div>
<p></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt; text-align: center;" dir="ltr"><span style="font-size: 18.6666666666667px; font-family: Arial; font-style: italic; vertical-align: baseline; white-space: pre-wrap;">100% of proceeds to benefit the family of Rob Fernandez - Donate </span><a style="text-decoration: none;" href="http://www.flavorus.com/wafform.aspx?_act=eventtickets&amp;_pky=302371"><span style="font-size: 18.6666666666667px; font-family: Arial; color: #1155cc; font-style: italic; vertical-align: baseline; white-space: pre-wrap; text-decoration: underline;">here</span></a></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt; text-align: center;" dir="ltr"><span style="font-size: 18.6666666666667px; font-family: Arial; color: #1155cc; font-style: italic; vertical-align: baseline; white-space: pre-wrap; text-decoration: underline;"><br /></span></div>
<p></span></span></span></span></div>
<div style="text-align: center;"><img style="border: 0pt none;" width="600" height="339" src="http://img.ymlp.com/plexipr_ROBFERNANDEZ_1.png" /></div>
<div style="text-align: center;">
<div class="p1" style="text-align: justify;">&nbsp;</div>
</div>
<div style="text-align: justify;"><span id="docs-internal-guid-36c0b7aa-70a6-bb6e-464a-5b5483496efe"></p>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="vertical-align: baseline; white-space: pre-wrap;">On Wednesday, September 16 the music community will come together to celebrate the life and legacy of NYC nightlife icon and legend </span><span style="font-weight: 700; vertical-align: baseline; white-space: pre-wrap;">Rob Fernandez. </span><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">Rob Fernandez, globally respected event promoter and a key architect of the New York nightlife scene, passed away on July 10, 2015. He was a primary figure in the city's entertainment culture for 25 years. &ldquo;</span><span style="color: #141823; font-style: italic; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">Dubbed the &lsquo;King of New York,&rsquo; Fernandez's inventive parties, keen eye for trends and talent, and generosity to stars, peers and upstarts alike made him a beloved figure throughout the global music industry,&rdquo; </span><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">says</span><span style="color: #141823; font-style: italic; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"> </span><a style="text-decoration: none;" href="http://www.billboard.com/articles/news/dance/6627200/rob-fernandez-new-york-promoter-dead"><span style="color: #1155cc; vertical-align: baseline; white-space: pre-wrap; text-decoration: underline; background-color: #ffffff;">Billboard</span></a><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">.</span></span></span></div>
<p><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><br /> </span></span></p>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">Tributes from across the globe from DJs, agents, music cohorts, friends, fans, and many more have poured in as documented on </span><a style="text-decoration: none;" href="https://www.facebook.com/groups/921975721197916/"><span style="color: #1155cc; vertical-align: baseline; white-space: pre-wrap; text-decoration: underline; background-color: #ffffff;">Facebook</span></a><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"> and by media outlets such as, </span><a style="text-decoration: none;" href="http://www.mixmag.net/read/obituary-rob-fernandez-blog"><span style="color: #1155cc; vertical-align: baseline; white-space: pre-wrap; text-decoration: underline; background-color: #ffffff;">Mixmag</span></a><span style="vertical-align: baseline; white-space: pre-wrap;"> and </span><a style="text-decoration: none;" href="https://thump.vice.com/en_us/article/dance-musics-biggest-djs-and-key-players-remember-rob-fernandez"><span style="color: #1155cc; vertical-align: baseline; white-space: pre-wrap; text-decoration: underline; background-color: #ffffff;">THUMP</span></a><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">. &nbsp;&nbsp;</span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 14.6666666666667px; font-family: Arial; color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="white-space: pre;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"> </span></span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">During Rob&rsquo;s tenure as a mega-promoter, he was generous to a fault and looked after everybody in his adopted nightlife &ldquo;family.&rdquo; To honor his legacy, many of the participating entities are donating their services to benefit Rob&rsquo;s immediate family -- everybody from the Pacha NYC club staff, Flavorus, Plexi PR, and the non-profit organization Lifebeat, to all the talent that will be performing for Rob, one last time.</span></span></span></div>
<p><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><br /> </span></span></p>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">An APB was sent out to agents: to give back to the man who helped launch and support the careers of countless DJs, and the DJs heeded the call. Here is the first phase of talent performing with more to be announced after Labor Day. </span></span></span></div>
<p><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><br /> </span></span></p>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">In alphabetical order:</span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><br /></span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">Behrouz</span><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="white-space: pre;"> </span></span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">Boris</span><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="white-space: pre;"> </span></span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">Cazzette</span><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="white-space: pre;"> </span></span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">Cevin Fisher</span><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="white-space: pre;"> </span></span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">Chris Liebing</span><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="white-space: pre;"> </span></span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">Chriss Vargas</span><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="white-space: pre;"> </span></span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">Cristian Arango</span><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="white-space: pre;"> </span></span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">Danny Krivit</span><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="white-space: pre;"> </span></span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">David Waxman</span><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="white-space: pre;"> </span></span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">Deniz Koyu</span><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="white-space: pre;"> </span></span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">DJTM</span><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="white-space: pre;"> </span></span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">Exacta</span><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="white-space: pre;"> </span></span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">Harry Romero</span><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="white-space: pre;"> </span></span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">Hector Romero</span><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="white-space: pre;"> </span></span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">Helena Legend</span><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="white-space: pre;"> </span></span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">Hex Hector</span><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="white-space: pre;"> </span></span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">Jason Ojeda</span><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="white-space: pre;"> </span></span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">Jean Pierre</span><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="white-space: pre;"> </span></span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">Jellybean Benitez</span><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="white-space: pre;"> </span></span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">Johnny Dynell</span><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="white-space: pre;"> </span></span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">Jonathan Peters</span><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="white-space: pre;"> </span></span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">Junior Sanchez</span><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="white-space: pre;"> </span></span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">Kaskade</span><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="white-space: pre;"> </span></span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">Kenny Dope</span><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="white-space: pre;"> </span></span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">Kirill Was Here</span><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="white-space: pre;"> </span></span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">Lady Bunny</span><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="white-space: pre;"> </span></span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">Lea Lorien</span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">Lord G</span><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="white-space: pre;"> </span></span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">Manny Freytes</span><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="white-space: pre;"> </span></span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">MJ Hall</span><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="white-space: pre;"> </span></span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">Merritt</span><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="white-space: pre;"> </span></span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">Mike Cruz</span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">Mike Whitmore</span><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="white-space: pre;"> </span></span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">Miss Jennifer</span><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="white-space: pre;"> </span></span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">Nick AC</span><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="white-space: pre;"> </span></span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">Paul Raffaele</span><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="white-space: pre;"> </span></span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">Richie Santana &amp; Peter Bailey</span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">Schoolly D</span><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="white-space: pre;"> </span></span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">Shahar</span><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="white-space: pre;"> </span></span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">Skribble</span><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="white-space: pre;"> </span></span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">Sleepy &amp; Boo</span><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="white-space: pre;"> </span></span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">T-Pro</span><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="white-space: pre;"> </span></span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">The Chainsmokers</span><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="white-space: pre;"> </span></span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">Theo</span><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="white-space: pre;"> </span></span><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="white-space: pre;"> </span></span></span></span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><i>Plus many more to be announced!</i></span></span></span></div>
<p><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><br /> </span></span></p>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="font-style: italic; vertical-align: baseline; white-space: pre-wrap;">Get involved with the House of Rob Celebration by volunteering time, talent or more by emailing: </span><a style="text-decoration: none;" href="mailto:info@houseofrob.com"><span style="color: #1155cc; font-style: italic; vertical-align: baseline; white-space: pre-wrap; text-decoration: underline;">info@houseofrob.com</span></a></span></span></div>
<p><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><br /> </span></span></p>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="font-style: italic; vertical-align: baseline; white-space: pre-wrap;">To purchase tickets or make additional donations please visit </span><a style="text-decoration: none;" href="http://www.flavorus.com/wafform.aspx?_act=eventtickets&amp;_pky=302371"><span style="color: #1155cc; font-style: italic; vertical-align: baseline; white-space: pre-wrap; text-decoration: underline;">here</span></a><span style="font-style: italic; vertical-align: baseline; white-space: pre-wrap;">. </span></span></span></div>
<div><span style="font-size: 14.6666666666667px; font-family: Arial; font-style: italic; vertical-align: baseline; white-space: pre-wrap;"><br /></span></div>
<p></span></div>
<div style="text-align: justify;"><img src="http://img.ymlp.com/plexipr_HORlineup_2.jpg" height="888" width="600" style="border: 0pt none;" /></div>
<div style="text-align: justify;">&nbsp;</div>
<div style="text-align: justify;"><span style="font-size: 10pt;"><span style="font-size: 12pt;"><span id="docs-internal-guid-abb042be-ffa4-c479-7e9a-956e576c182c"></p>
<div style="line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span id="docs-internal-guid-36c0b7aa-70a7-ca02-ba65-832be751c1cc"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"></p>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="vertical-align: baseline; white-space: pre-wrap;">September 16, 2015</span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-weight: 700; vertical-align: baseline; white-space: pre-wrap;">House of Rob Celebration</span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="vertical-align: baseline; white-space: pre-wrap;">West 46th Street </span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="vertical-align: baseline; white-space: pre-wrap;">New York, NY</span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="vertical-align: baseline; white-space: pre-wrap;">Tickets available </span><a style="text-decoration: none;" href="http://www.flavorus.com/wafform.aspx?_act=eventtickets&amp;_pky=302371"><span style="color: #1155cc; vertical-align: baseline; white-space: pre-wrap; text-decoration: underline;">here</span></a><span style="vertical-align: baseline; white-space: pre-wrap;">.</span></div>
<p></p>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><a style="text-decoration: none;" href="http://www.houseofrobnyc.com"><span style="color: #1155cc; vertical-align: baseline; white-space: pre-wrap; text-decoration: underline;">www.HOUSEOFROBNYC.com</span></a></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="vertical-align: baseline; white-space: pre-wrap;">#HOUSEOFROB</span></div>
<p></p>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><a style="text-decoration: none;" href="https://www.facebook.com/rpmpresents"><span style="color: #1155cc; vertical-align: baseline; white-space: pre-wrap; text-decoration: underline;">Facebook.com/RPMPresents</span></a></div>
<p><a style="text-decoration: none;" href="https://twitter.com/rpm_presents"><span style="color: #1155cc; vertical-align: baseline; white-space: pre-wrap; text-decoration: underline;">Twitter.com/RPM_presents</span></a></span></span></span></div>
<div style="line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr">&nbsp;</div>
<p></span></span></span></div>
<div style="text-align: justify;">
<div style="line-height: 1.15; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;" dir="ltr">
<div style="color: #222222; font-family: arial, sans-serif; font-size: 13px; background-color: #ffffff;">
<div>
<div>&nbsp;</div>
<div><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><br /></span></span></div>
<div dir="ltr" style="line-height: 1.15; text-align: center; margin-bottom: 0pt; margin-top: 0pt;"><span style="font-size: 10pt;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">&nbsp;###</span></span></span></div>
<p><span style="font-family: arial, helvetica, sans-serif;"><span style="font-size: 10pt;"><br style="text-align: center;" /> </span> </span></p>
<div dir="ltr" style="line-height: 1.15; margin-bottom: 0pt; margin-top: 0pt;"><span style="font-size: 10pt;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">For all media inquiries, please contact:</span></span></span></div>
<div dir="ltr" style="line-height: 1.15; margin-bottom: 0pt; margin-top: 0pt;"><span style="font-size: 10pt;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">Betty Kang |&nbsp;<a href="mailto:betty@plexipr.com" target="_blank" style="color: #1155cc;">betty@plexipr.com</a></span></span></span></div>
<div dir="ltr" style="line-height: 1.15; margin-bottom: 0pt; margin-top: 0pt;"><span style="line-height: 1.15;"><span style="font-size: 10pt;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">Dance Local. Think Global.</span></span></span></span></div>
<div dir="ltr" style="line-height: 1.15; margin-bottom: 0pt; margin-top: 0pt;"><span style="font-size: 10pt;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">&nbsp;</span></span></span></div>
</div>
</div>
</div>
</div>
<p></body><br />
</html></p>
