---
title: Movement 08 Announces Festival Attendance, Recycling Program Success
date: 2008-06-17 13:07:45 -04:00
categories:
- News
tags:
- Movement
- DEMF
- Paxahau
- Detroit Music Festival
- Detroit
layout: post
status: publish
author:
  display_name: Admin
  login: admin
  email: brian@plexipr.com
  url: http://www.plexipr.com
author_login: admin
author_email: brian@plexipr.com
author_url: http://www.plexipr.com
wordpress_id: 204
wordpress_url: http://www.plexipr.com/2008/06/17/movement-08-announces-festival-attendance-recycling-program-success/
date_gmt: '2008-06-17 18:07:45 -0400'
---

<p align="center"><a href="http://www.mydemf.com"><img title="Detroit Electronic Music Festival" src="http://www.plexipr.com/%7Eplexiftp/Movement08/movement_logo_withdates_600.jpg" alt="" width="414" height="73" /></a></p>
<p align="center">
<p align="center"><strong>MOVEMENT 08 - DETROIT'S ELECTRONIC MUSIC FESTIVAL </strong><strong><br />
<em>DANCES TO RECORD BREAKING ATTENDANCE AND INAUGURAL RECYCLING PROGRAM COLLECTS MORE THAN 3,000 POUNDS OF RECYCLABLES</em></strong></p>
<p>Paxahau, producers of Movement 08 - Detroit's Electronic Music Festival, announced that attendance of this year's three-day festival surpassed 80,000, toppling last year's attendance and exceeding the set goal of 60,000.  Attendance numbers were based on implementing the use of turnstiles and tracking festival VIP's as well.  This year marked the first time the festival tracked attendance using turnstiles.</p>
<p><em>"We anticipated a surge in attendance, as presales were triple what they were last year three weeks before the festival,"</em> stated Jason Huvaere, festival director, Paxahau Promotions Group. <em> "It's amazing to now have actual attendance numbers that equate to real economic benefits for the City of Detroit, as well as the festival, and exhibits the venue's true capacity." </em></p>
<p>On top of attendance success, the recycling program instituted by Paxahau collected more than 3,000 pounds of recyclables including plastic, fiber, and cans over the three-day event.  Paxahau teamed up with Recycle Detroit, a non-profit organization founded by Detroiter Sarah Kubik; Omar S. George of WasteONE in Clinton Township; and Great Lakes Recycling of Roseville to collect recyclable materials.</p>
<p>The festival had approximately 10 recycling tents, staffed with volunteers that collected cans, bottles, and paper.  Great Lakes Recycling, offering single stream capabilities, stored and processed all the recyclable materials, and once separated, the recyclables were transferred to a single location for further processing.</p>
<p>Huvaere added, <em>"We experienced a remarkable and memorable event this year.  Reaction from everyone involved, including sponsors, artists, media, and fans was incredibly positive.  We definitely set a new benchmark for the festival, and I am excited about planning next year's event." </em></p>
<p>Movement interest, on all levels, was a direct result of Paxahau's dedication and hard work to continually upgrade the festival experience, from the artist line-up to the drastically enhanced sound systems as well as upgraded staging to protect from inclement weather.</p>
<p>Much of the anticipation surrounding Movement 08 was generated by one of the strongest lineups the festival has had in its history.  This year's roster of performers included Moby, Benny Benassi, Carl Craig, Richie Hawtin, Deadmau5, James Zabiela, Dubfire, and critically acclaimed artists such as The Cool Kids, Peanut Butter Wolf and Cobblestone Jazz.</p>
<p><em>"We're all about showcasing renowned, established artists while also giving up-and-coming talent an opportunity to reach a broader audience,"</em> said Huvaere.  <em>"Most important, however, the festival further expands Detroit's reputation for inspiring the electronic music scene - and the foundation for the creative renaissance being led by electronic music artists everywhere who recognize the importance of being a part of this cultural phenomenon."</em></p>
<p><strong>Upcoming Paxahau events:</strong><br />
Friday, July 4th at 6:00 p.m. - Cityfest, Pure Detroit Stage, Paxahau Presents King Britt and Ryan Elliott<br />
Labor Day Weekend - Paxahau Ten Year Anniversary</p>
<p><strong>About Paxahau</strong><br />
Since 1998 Paxahau has promoted electronic music and has grown to include a web archive, booking agency, record label and an event production company which produces an average of 12 events a year.  With a network of alliances and resources that span the globe, Paxahau has emerged as a premier promotions group within the electronic music industry.  Paxahau is committed to further establishing the Detroit Electronic Music Festival as North America's most prominent electronic music venue, which will continue to be a foundation for the creative renaissance being led by electronic music artists everywhere.  Please visit <a href="http://t.ymlp43.com/yjjafauehanauyhjaoajshq/click.php" target="_blank">myspace.com/detroitmusicfest</a> to find the latest news as it develops.</p>
