---
title: 'MOVEMENT 08: Detroit''s Electronic Music Festival From May 24-26, 2008'
date: 2008-04-30 10:02:59 -04:00
categories:
- Events
- WMC
- News
- Festivals
tags:
- Movement 2008
- Detroit Electronic Music Festival
layout: post
status: publish
author:
  display_name: Admin
  login: admin
  email: brian@plexipr.com
  url: http://www.plexipr.com
author_login: admin
author_email: brian@plexipr.com
author_url: http://www.plexipr.com
wordpress_id: 186
wordpress_url: http://www.plexipr.com/2008/04/30/movement-08-detroits-electronic-music-festival-from-may-24-26-2008/
date_gmt: '2008-04-30 15:02:59 -0400'
---

<p style="text-align: center;"><a href="http://www.mydemf.com"><img class="size-medium wp-image-1046 aligncenter" title="DEMF" src="http://www.plexipr.com/wp-content/uploads/2008/04/movement_logo_withdates_600-300x53.jpg" alt="DEMF" width="300" height="53" /></a></p>
<p style="text-align: center;"><strong>MOVEMENT 08 CELEBRATES THE ENERGY, INNOVATION AND CULTURE OF ELECTRONIC MUSIC<br />
MEMORIAL DAY WEEKEND MAY 24-26, 2008<br />
AT HART PLAZA</strong></p>
<p style="text-align: center;"><em>Detroit Electronic Music Festival Showcases Strong Artist Line Up, Weatherproofed Stages, And Enhanced Sound System That Create A Diverse Music Experience</em></p>
<p>Detroit's Electronic Music Festival has become one of the most highly anticipated annual events for electronic music fans in Detroit and across the globe. And <strong>Movement 08</strong> - coming <span style="text-decoration: underline;"><strong>May 24-26</strong></span> at Detroit's Hart Plaza - is no exception. With an unprecedented lineup of artists and numerous new elements, Movement 08 promises to be the most exciting, entertaining and innovative festival yet.</p>
<p><em>"Our philosophy for producing Detroit's Electronic Music Festival is grounded in our company's mission, to accelerate and accentuate all the best of what Detroit has to offer the world, and that includes: artists, events, destinations, and all forms of cultural enrichment," said Jason Huvaere, Paxahau Promotions Group, which has produced this festival since 2006. "That also includes making improvements to the festival year after year, to help it grow and spread the excitement of the electronic music culture to people across the area and around the world."</em></p>
<p>Much of the anticipation surrounding Movement 08 is being generated by one of the strongest lineups the festival has had in its history. This year's roster of performers includes Moby, Benny Benassi, Carl Craig, Richie Hawtin, Deadmau5, James Zabiela, Dubfire, and critically acclaimed artists such as Marco Carola, Peanut Butter Wolf and Cobblestone Jazz. Although Paxahau actively heralds Detroit's heritage as the birthplace of techno, the company also experiences the talent from other cities, such as Miami and Berlin, to bring artists from every corner of the world to Movement.</p>
<p><em>"We're attentive to the pulse of the music community, so we can present artists that expand Movement's dream - and expose audiences to the spectrum of diverse genres within the electronic music scene," stated Huvaere. "We're all about showcasing renowned, established artists while also giving up-and-coming talent an opportunity to reach a broader audience."</em></p>
<p>New Stages Elevate Movement 08 To Higher Standards Of Excellence<br />
The festival will feature four distinct stages - each with its own unique personality. The vitaminwater Stage, the Beatport Stage, the Real Detroit Stage and the Red Bull Stage. This is the first year the Red Bull Music Academy is presenting a stage at any US festival.</p>
<p>Huvaere added, "Like Paxahau, the Red Bull Music Academy is dedicated to helping artists gain exposure and experience while meeting and collaborating with other artists from around the world - creating a real cultural phenomenon, just like Detroit's Electronic Music Festival."</p>
<p>The Red Bull Stage and the Beatport Stage represent two of the most significant improvements to this year's festival. Both stages feature new structure designs to provide the audience with an optimal listening and dancing experience. The stages include new vinyl roofs and metal structures, ensuring a foundation strong enough to hold the sound and lighting systems. Plus, the stages provide more space, better sightlines and protection against inclement weather conditions. In addition to these new stages, the festival will feature drastically enhanced sound systems to provide attendees with outstanding sound quality.</p>
<p><strong>Sponsors Help Maintain Forward Momentum</strong><br />
Subsidizing stages is only one way sponsors are supporting Movement 08, one of only four electronic music events held in North America. In fact, as economic conditions have resulted in declining funding from other sources, sponsorships are more important than ever before to the ongoing success of the festival - and Paxahau's ability to keep ticket prices affordable.</p>
<p>In addition to Red Bull, vitaminwater, Real Detroit Weekly and Beatport - the leading music download site of the electronic music industry, which only sponsors three other events in the U.S. each year - other key sponsors of Movement 08 include Scion, MySpace, Sony Playstation, Garden Fresh, Nino Salvaggio International Marketplace, Moo Moo's Cuisine and Resident Advisor, an online magazine devoted to dance music and club culture.</p>
<p><em>"Without this support, this event does not happen. These presenters understand the value and unique opportunity to reach the hearts and minds of electronic music fans, a cultural demographic that doesn't respond to traditional marketing and advertising - but is loyal to companies and brands that get behind the things they are passionate about."</em></p>
<p><strong>Join The Movement</strong><br />
Held over Memorial Day Weekend (May 24-26) at Downtown Detroit's Hart Plaza, Movement 08 is expected to attract up to 20,000 attendees per day. Discounted pre-sale admission tickets to the festival are $40 for a weekend pass (available for a limited time only) or $175 for VIP tickets (with limited capacity available). The festival's hours are 12 Noon to Midnight.</p>
<p>Music fans from all over the region, the country and the world will visit Detroit to attend Detroit's Electronic Music Festival, bringing much-needed revenue to the City of Detroit and Southeastern Michigan. Most important, however, the festival will further expand Detroit's reputation for inspiring the electronic music scene - and the foundation for the creative renaissance being led by electronic music artists everywhere.</p>
<p><em>"As electronic music has evolved and expanded its reach, the festival has grown and improved right along with it," said Jason Huvaere. "The best way to appreciate and understand what makes this event special is to come and experience it."</em></p>
<p>For more information on Movement 08 - Detroit's Electronic Music Festival or to order tickets, visit <a href="http://">www.myspace.com/detroitmusicfest</a> or <a href="http://">www.paxahau.com</a>.</p>
<p><span style="text-decoration: underline;"><strong>MOVEMENT 08 ARTIST LINE-UP</strong></span><br />
ALEX SMOKE -LIVE<br />
ALEX UNDER -LIVE<br />
ALLAND BYALLO<br />
ALTON MILLER<br />
BENNY BENASSI<br />
BIG JOE HIX<br />
BRIAN KAGE &amp; LUKE HESS "REFERENCE"<br />
CARL CRAIG -LIVE<br />
CASSY<br />
COBBLESTONE JAZZ -LIVE<br />
DARKCUBE -LIVE<br />
DAVIDE SQUILLACE<br />
DBX -LIVE<br />
DEADMAU5 -LIVE<br />
DEEPCHORD PRESENTS ECHOSPACE -LIVE<br />
DEREK PLASLAIKO<br />
DERRICK THOMPSON AKA DRIVETRAIN<br />
DIESELBOY &amp; MC MESSINIAN<br />
DREW POMPA<br />
DUBFIRE<br />
EGYPTIAN LOVER -LIVE<br />
ELECTROBOUNCE.COM PRESENTS DATABASS GHETTO TECH<br />
ERIC JOHNSTON -LIVE<br />
GABE REAL<br />
GIRL TALK -LIVE<br />
GUILLAUME &amp; THE COUTU DUMONTS -LIVE<br />
HALF HAWAII -LIVE<br />
HEARTTHROB -LIVE<br />
JAMES ZABIELA<br />
JERRY ABSTRACT<br />
JORIS VOORN -LIVE<br />
JOSH DAHLBERG -LIVE<br />
JOSH WINK<br />
JUSTIN KRUSE AKA KRUSE KONTROL<br />
JUSTIN LONG<br />
KEITH WORTHY<br />
KENNETH THOMAS<br />
KEVIN SAUNDERSON<br />
KONRAD BLACK<br />
LAWNCHAIR GENERALS<br />
LEE BURRIDGE<br />
MAGDA<br />
MARCO CAROLA<br />
MARK FARINA<br />
MATHIAS KADEN -LIVE<br />
MATTHEW HAWTIN<br />
MICHAEL GEIGER<br />
MIKE GRANT<br />
MILES MAEDA<br />
MINX<br />
MOBY<br />
MR. DE' -LIVE/DJ<br />
NEWCLEUS -LIVE<br />
NOSPECTACLE -LIVE<br />
OSCAR MULERO<br />
PAR GRINDVIK -LIVE<br />
PAUL RITCH -LIVE<br />
PEANUT BUTTER WOLF<br />
PETE ROCK<br />
PUNISHER - DJ SET<br />
REGGIE "HOTMIX" HARRELL<br />
REX SEPULVEDA -LIVE<br />
RICHIE HAWTIN<br />
RICH KORACH<br />
SHAWN MICHAELS<br />
SOUNDMURDERER<br />
SPEEDY J -LIVE W/ SCOTT PAGANO VJ<br />
STACEY PULLEN<br />
T LINDER<br />
TECH ITCH<br />
TERRENCE PARKER<br />
THE COOL KIDS -LIVE<br />
THE NICK SPEED COLLECTION<br />
TWONZ<br />
TYCHO -LIVE<br />
YOS<br />
ZIP</p>
