---
title: "*NEW LOCATION* RPM Presents Nicole Moudaber  Friends at Brooklyn Mirage this
  Saturday, September 12"
date: 2015-09-10 15:27:05 -04:00
categories:
- Uncategorized
- Releases
layout: post
status: publish
author:
  display_name: Admin
  login: admin
  email: brian@plexipr.com
  url: http://www.plexipr.com
author_login: admin
author_email: brian@plexipr.com
author_url: http://www.plexipr.com
wordpress_id: 6543
wordpress_url: http://ymlp.com/z8tesP
date_gmt: '2015-09-10 20:27:05 -0400'
---

<p><html><br />
<head><br />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/></head><br />
<body>
<div><span style="font-size: 10pt;"><b><span style="font-family: arial, helvetica, sans-serif;">FOR IMMEDIATE RELEASE</span></b></span></div>
<div style="text-align: center;"><b><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><br /></span></span></b></div>
<div style="text-align: center;"><b><span style="font-size: 10pt;"><span style="font-size: 12pt;"><span style="font-family: arial, helvetica, sans-serif;"><img style="border: 0pt none;" width="371" height="96" src="http://img.ymlp.com/plexipr_plexiprplexiprNicoleMoudaberLogo1.jpg" /></span></span></span></b></div>
<div style="text-align: center;">&nbsp;</div>
<div style="text-align: center;"><b><span style="font-size: 10pt;"><span style="font-size: 12pt;"><span style="font-family: arial, helvetica, sans-serif;"><img height="100" src="http://img.ymlp.com/plexipr_RPMLOGO_1.jpg" width="100" style="border: 0pt none;" />&nbsp; &nbsp; &nbsp;&nbsp;<img src="http://img.ymlp.com/plexipr_HORlogo_1.jpg" height="83" width="100" style="border: 0pt none;" /><br /></span></span></span></b></div>
<div style="text-align: center;">&nbsp;</div>
<div style="text-align: center;"><span style="font-size: 10pt;"><span style="font-size: 12pt;"><span style="font-family: arial, helvetica, sans-serif;"><span id="docs-internal-guid-abb042be-ffa2-4f61-b320-dca44ed7bf0c"></p>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt; text-align: center;" dir="ltr"><span id="docs-internal-guid-f7192eea-b859-8db3-6bbc-8b91eabbf1ad"></p>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt; text-align: center;" dir="ltr"><span style="font-size: 18.6667px; font-family: Arial; font-weight: 700; vertical-align: baseline; white-space: pre-wrap;">Nicole Moudaber &amp; Friends </span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt; text-align: center;" dir="ltr"><span style="font-size: 18.6667px; font-family: Arial; font-weight: 700; vertical-align: baseline; white-space: pre-wrap;">&lsquo;BREED&rsquo; EP Official Release Party - Saturday, September 12</span></div>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt; text-align: center;" dir="ltr"><span style="font-size: 18.6667px; font-family: Arial; font-weight: 700; vertical-align: baseline; white-space: pre-wrap;">with Victor Calderone, Joel Mull, Hector and Lauren Lane</span></div>
<p></p>
<div style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt; text-align: center;" dir="ltr"><span style="font-size: 18.6667px; font-family: Arial; font-weight: 700; font-style: italic; vertical-align: baseline; white-space: pre-wrap;">**New Location: The Brooklyn Mirage**</span></div>
<div style="line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; text-align: center;" dir="ltr"><span style="font-size: 18.6667px; font-family: Arial; font-weight: 700; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">99 Scott Ave. Brooklyn, NY</span></div>
<p><span style="font-size: 16px; font-family: Arial; color: #222222; font-style: italic; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">[YouTube] Nicole Moudaber &amp; Skin "Someone Like You"-- Watch</span><a style="text-decoration: none;" href="https://www.youtube.com/watch?v=oUqFjeH4XjQ"><span style="font-size: 16px; font-family: Arial; color: #222222; font-style: italic; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"> </span><span style="font-size: 16px; font-family: Arial; color: #1155cc; font-style: italic; vertical-align: baseline; white-space: pre-wrap; text-decoration: underline; background-color: #ffffff;">here</span></a><span style="font-size: 16px; font-family: Arial; color: #222222; font-style: italic; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"> </span></span></div>
<p></span></span></span></span></div>
<div style="text-align: center;"><span style="font-size: 18.6666666666667px; font-family: Arial; font-style: italic; vertical-align: baseline; white-space: pre-wrap;"><br /></span></div>
<div style="text-align: center;"><img src="http://img.ymlp.com/plexipr_NicoleMoudaber003X2386_1.jpg" height="600" width="400" style="border: 0pt none;" /></div>
<div style="text-align: center;">&nbsp;</div>
<div style="text-align: center;">
<div class="p1" style="text-align: justify;"><span id="docs-internal-guid-f7192eea-b859-c6ea-cdf3-241edef18d49"></p>
<div style="line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="vertical-align: baseline; white-space: pre-wrap;">Before New York&rsquo;s summer fizzles out, </span><span style="font-weight: 700; font-style: italic; vertical-align: baseline; white-space: pre-wrap;">MOOD Records</span><span style="font-style: italic; vertical-align: baseline; white-space: pre-wrap;"> </span><span style="vertical-align: baseline; white-space: pre-wrap;">label head </span><span style="font-weight: 700; vertical-align: baseline; white-space: pre-wrap;">Nicole Moudaber</span><span style="vertical-align: baseline; white-space: pre-wrap;"> will heat things up with an official release party for her upcoming &lsquo;BREED&rsquo; EP at her </span><span style="font-weight: 700; font-style: italic; vertical-align: baseline; white-space: pre-wrap;">Nicole Moudaber &amp; Friends</span><span style="vertical-align: baseline; white-space: pre-wrap;"> showcase this </span><span style="vertical-align: baseline; white-space: pre-wrap; text-decoration: underline;">Saturday, September 12</span><span style="vertical-align: baseline; white-space: pre-wrap;">. Due to overwhelming demand the event has been moved from Coney Island to the most buzzed about New York venue this summer, </span><span style="font-weight: 700; vertical-align: baseline; white-space: pre-wrap;">The Brooklyn Mirage</span><span style="vertical-align: baseline; white-space: pre-wrap;">, located at</span><span style="color: #ff0000; vertical-align: baseline; white-space: pre-wrap;"> </span><span style="vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">99 Scott Ave. Brooklyn, NY</span><span style="color: #ff0000; vertical-align: baseline; white-space: pre-wrap;">.</span></span></span></div>
<p><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><br /> </span></span></p>
<div style="line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="vertical-align: baseline; white-space: pre-wrap;">Created by </span><span style="font-style: italic; vertical-align: baseline; white-space: pre-wrap;">Reynard Productions</span><span style="vertical-align: baseline; white-space: pre-wrap;">, The Brooklyn Mirage is a new outdoor and indoor event space in East Williamsburg open only this summer, July through September. With expansive KV2 Audio to immerse attendees in crystalline sound, meticulously designed to create a sense of warmth and intimacy, platforms and levels for viewing Brooklyn and the city, an indoor lounge for breaks during the day, fine dine and drink, creature comforts and so many other details left to surprise, it is truly a Mirage: now you see the dream, at summer's end you won't. </span></span></span></div>
<p><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><br /> </span></span></p>
<div style="line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="vertical-align: baseline; white-space: pre-wrap;">The open air show will feature a slew of talent from techno's major players with Nicole Moudaber performing back-to-back with </span><span style="font-weight: 700; vertical-align: baseline; white-space: pre-wrap;">Victor Calderone</span><span style="vertical-align: baseline; white-space: pre-wrap;"> along with sets from Swedish connoisseur </span><span style="font-weight: 700; vertical-align: baseline; white-space: pre-wrap;">Joel Mull</span><span style="vertical-align: baseline; white-space: pre-wrap;">, Vatos Locos don</span><span style="font-weight: 700; vertical-align: baseline; white-space: pre-wrap;"> Hector</span><span style="vertical-align: baseline; white-space: pre-wrap;">, New York native </span><span style="font-weight: 700; vertical-align: baseline; white-space: pre-wrap;">Lauren Lane</span><span style="vertical-align: baseline; white-space: pre-wrap;"> and a special warm up set from </span><span style="font-weight: 700; vertical-align: baseline; white-space: pre-wrap;">Nicole Moudaber</span><span style="vertical-align: baseline; white-space: pre-wrap;">! </span></span></span></div>
<div style="line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="vertical-align: baseline; white-space: pre-wrap;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"> </span></span></span></div>
<div style="line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="vertical-align: baseline; white-space: pre-wrap;">Nicole is dedicating this </span><span style="font-style: italic; vertical-align: baseline; white-space: pre-wrap;">RPM Presents</span><span style="vertical-align: baseline; white-space: pre-wrap;"> show to the &lsquo;</span><span style="font-weight: 700; vertical-align: baseline; white-space: pre-wrap;">HOUSE OF ROB</span><span style="vertical-align: baseline; white-space: pre-wrap;">,&rsquo; the legacy left behind by NYC nightlife icon and legend </span><span style="font-weight: 700; vertical-align: baseline; white-space: pre-wrap;">Rob Fernandez</span><span style="vertical-align: baseline; white-space: pre-wrap;">. Rob was instrumental in introducing Nicole to the NYC stage and championed her as he often did for artists that he believed in. His legacy and genius live on in each party and every beat on the dancefloor. </span><span style="color: #222222; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">Nicole will donate a portion of the proceeds to the Fernandez Family. </span></span></span></div>
<div style="line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="vertical-align: baseline; white-space: pre-wrap;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"> </span></span></span></div>
<div style="line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="vertical-align: baseline; white-space: pre-wrap;">Nicole states: </span><span style="font-style: italic; vertical-align: baseline; white-space: pre-wrap;">&ldquo;I'm having this show with a lot of sadness in my heart, but also knowing that Rob is above me with a smile. I decided to dedicate this event to him because of the circumstances. I wasn't sure the event was going to happen when Rob left us but RPM wanted to go ahead with it. It is a very special one. It's my first festival and it&rsquo;s in New York City and he won't be there to see it. The only idea that keeps me going is that he would have wanted it to happen. And I want to do everything to channel all the energy on that special day, for Rob.&rdquo; </span></span></span></div>
<div style="line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="vertical-align: baseline; white-space: pre-wrap;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"> </span></span></span></div>
<div style="line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="vertical-align: baseline; white-space: pre-wrap;">Ambassador of dark and driving techno,</span><span style="font-weight: 700; vertical-align: baseline; white-space: pre-wrap;"> Nicole Moudaber </span><span style="vertical-align: baseline; white-space: pre-wrap;">has teamed up with </span><span style="font-weight: 700; vertical-align: baseline; white-space: pre-wrap;">Skin</span><span style="vertical-align: baseline; white-space: pre-wrap;">, the multi-talented </span><span style="font-style: italic; vertical-align: baseline; white-space: pre-wrap;">Skunk Anansie </span><span style="vertical-align: baseline; white-space: pre-wrap;">frontwoman, established DJ and fashion icon, for a collaborative EP entitled &lsquo;BREED&rsquo;. Two legendary artists in their own right, Moudaber and Skin have brought together cutting-edge creative and visual aesthetics to ensure &lsquo;BREED&rsquo; is an assault on the senses. The exceptional songwriting and performance abilities of Skin coupled with Moudaber&rsquo;s production finesse both point to &lsquo;BREED&rsquo; being one of the most celebrated conceptual projects in techno. &lsquo;BREED&rsquo; is out September 18 on </span><span style="font-style: italic; vertical-align: baseline; white-space: pre-wrap;">MOOD Records</span><span style="vertical-align: baseline; white-space: pre-wrap;">. </span><span style="color: #222222; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">Following the launch of the video for their first single "</span><a style="text-decoration: none;" href="https://www.youtube.com/watch?v=1YkZvrbbyqQ"><span style="color: #1155cc; vertical-align: baseline; white-space: pre-wrap; text-decoration: underline; background-color: #ffffff;">You Like This</span></a><span style="color: #222222; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">" Nicole Moudaber &amp; Skin have released their second track of their double single release, &ldquo;</span><a style="text-decoration: none;" href="https://www.youtube.com/watch?v=oUqFjeH4XjQ"><span style="color: #1155cc; vertical-align: baseline; white-space: pre-wrap; text-decoration: underline; background-color: #ffffff;">Someone Like You</span></a><span style="color: #222222; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">&rdquo; both available now on </span><a style="text-decoration: none;" href="https://pro.beatport.com/release/someone-like-you/1585365"><span style="color: #1155cc; vertical-align: baseline; white-space: pre-wrap; text-decoration: underline; background-color: #ffffff;">Beatport</span></a><span style="color: #222222; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">. </span></span></span></div>
<div style="line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="vertical-align: baseline; white-space: pre-wrap;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"> </span></span></span></div>
<div style="line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="font-style: italic; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">Nicole Moudaber &amp; Friends at The Brooklyn Mirage tickets are on sale now </span><a style="text-decoration: none;" href="http://www.flavorus.com/wafform.aspx?_act=eventtickets&amp;_pky=299559"><span style="color: #1155cc; font-style: italic; vertical-align: baseline; white-space: pre-wrap; text-decoration: underline; background-color: #ffffff;">here</span></a><span style="font-style: italic; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">. </span></span></span></div>
<div><span style="font-size: 14.6667px; font-family: Arial; font-style: italic; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><br /></span></div>
<p></span></div>
</div>
<div style="text-align: justify;"><img src="http://img.ymlp.com/plexipr_NM912updated_1.jpg" height="500" width="500" style="border: 0pt none;" /></div>
<div style="text-align: justify;">&nbsp;</div>
<div style="text-align: justify;"><span style="font-size: 10pt;"><span style="font-size: 12pt;"><span id="docs-internal-guid-abb042be-ffa4-c479-7e9a-956e576c182c"></p>
<div style="line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; text-align: center;" dir="ltr"><span id="docs-internal-guid-f7192eea-b85a-f966-6285-f59a06bf46bb"></p>
<div style="line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;" dir="ltr"><span style="vertical-align: baseline; white-space: pre-wrap;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">September 12, 2015</span></span></span></div>
<div style="line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;" dir="ltr"><span style="font-style: italic; vertical-align: baseline; white-space: pre-wrap;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">RPM Presents</span></span></span></div>
<div style="line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;" dir="ltr"><span style="font-weight: 700; vertical-align: baseline; white-space: pre-wrap;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">Nicole Moudaber &amp; Friends</span></span></span></div>
<div style="line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;" dir="ltr"><span style="vertical-align: baseline; white-space: pre-wrap;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">Nicole Moudaber b2b Victor Calderone</span></span></span></div>
<div style="line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;" dir="ltr"><span style="vertical-align: baseline; white-space: pre-wrap;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">Joel Mull</span></span></span></div>
<div style="line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;" dir="ltr"><span style="vertical-align: baseline; white-space: pre-wrap;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">Hector</span></span></span></div>
<div style="line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;" dir="ltr"><span style="vertical-align: baseline; white-space: pre-wrap;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">Lauren Lane</span></span></span></div>
<div style="line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;" dir="ltr"><span style="vertical-align: baseline; white-space: pre-wrap;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">Special Nicole Moudaber warm up set</span></span></span></div>
<p><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><br /> </span></span></p>
<div style="line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;" dir="ltr"><span style="vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">The Brooklyn Mirage</span></span></span></div>
<div style="line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">99 Scott Ave. Brooklyn, NY 11237</span><span style="vertical-align: baseline; white-space: pre-wrap;"> </span></span></span></div>
<div style="line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;" dir="ltr"><span style="vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">4pm - late</span></span></span></div>
<div style="line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;" dir="ltr"><span style="vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">Rain or Shine</span></span></span></div>
<div style="line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="vertical-align: baseline; white-space: pre-wrap;">Tickets on sale now via</span><span style="color: #ff0000; vertical-align: baseline; white-space: pre-wrap;"> </span><a style="text-decoration: none;" href="http://www.flavorus.com/wafform.aspx?_act=eventtickets&amp;_pky=299559"><span style="color: #1155cc; font-weight: 700; vertical-align: baseline; white-space: pre-wrap; text-decoration: underline;">Flavorus</span></a><span style="vertical-align: baseline; white-space: pre-wrap;">.</span></span></span></div>
<div style="line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;" dir="ltr"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap;">Subway: Take the L toward </span><span style="color: #2c2c2c; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;">Canarsie - Rockaway Pkwy to the</span><span style="color: #141823; vertical-align: baseline; white-space: pre-wrap;"> Jefferson Street stop </span></span></span></div>
<p><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><br /> </span></span></p>
<div style="line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;" dir="ltr"><span style="font-weight: 700; vertical-align: baseline; white-space: pre-wrap; text-decoration: underline;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">Nicole Moudaber Tour Dates</span></span></span></div>
<div style="line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;" dir="ltr"><span style="vertical-align: baseline; white-space: pre-wrap;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">September 12 &nbsp;Brooklyn, NY @ The Brooklyn Mirage | Nicole Moudaber &amp; Friends</span></span></span></div>
<div style="line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;" dir="ltr"><span style="vertical-align: baseline; white-space: pre-wrap;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">September 13 &nbsp;Las Vegas, NV @ DayLight Beach Club</span></span></span></div>
<div style="line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;" dir="ltr"><span style="vertical-align: baseline; white-space: pre-wrap;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">September 18 &nbsp;Miami, FL @ Trade</span></span></span></div>
<div style="line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;" dir="ltr"><span style="vertical-align: baseline; white-space: pre-wrap;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">September 19 &nbsp;Montreal, QC Canada @ Stereo</span></span></span></div>
<div style="line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;" dir="ltr"><span style="vertical-align: baseline; white-space: pre-wrap;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">September 25 &nbsp;Chicago, IL @ The Mid</span></span></span></div>
<div style="line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;" dir="ltr"><span style="vertical-align: baseline; white-space: pre-wrap;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">September 27 &nbsp;Denver, CO @ Beta</span></span></span></div>
<div style="line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;" dir="ltr"><span style="color: #222222; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">October 1 Ciudad Juarez, MX @ Hardpop</span></span></span></div>
<div style="line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;" dir="ltr"><span style="vertical-align: baseline; white-space: pre-wrap;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">October 2 &nbsp;Houston, TX @ Stereo Live</span></span></span></div>
<div style="line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;" dir="ltr"><span style="color: #222222; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">October 3 San Jose, CR @ Club Vertigo</span></span></span></div>
<div><span style="font-size: 14.6667px; font-family: Arial; color: #222222; vertical-align: baseline; white-space: pre-wrap; background-color: #ffffff;"><br /></span></div>
<p></span><img src="http://img.ymlp.com/plexipr_119477389150363219015071726455116510655189o_1.jpg" height="292" width="600" style="border: 0pt none;" /></div>
<div style="line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; text-align: center;" dir="ltr"><span id="docs-internal-guid-f7192eea-b85c-aee0-97a6-7b856a9adef1"><span style="font-style: italic; vertical-align: baseline; white-space: pre-wrap;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">The Brooklyn Mirage // Photo credit: Amanda Kari McHugh</span></span></span></span></div>
<div style="line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;" dir="ltr"><span style="font-style: italic; vertical-align: baseline; white-space: pre-wrap;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><br /></span></span></span></div>
<p></span></span></span></div>
<div style="text-align: center;">
<div class="p1">
<div align="center">
<div align="center"><span id="docs-internal-guid-878c785e-7b32-8cb1-073d-b507abb4ffa2"></p>
<div dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;"><span id="docs-internal-guid-f7456d70-3472-7063-574a-e0b492dd5b27"> </span></div>
<div dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;">&nbsp;</div>
<p></span></div>
</div>
</div>
</div>
<div style="text-align: justify;">
<div style="line-height: 1.15; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;" dir="ltr">
<div style="color: #222222; font-family: arial, sans-serif; font-size: 13px; background-color: #ffffff;">
<div dir="ltr" style="line-height: 1.15; margin-top: 0pt; margin-bottom: 0pt;">
<div style="font-weight: bold;"><span style="font-size: 10pt;"><span style="font-size: 10pt;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">For more information on Nicole Moudaber:</span></span></span></span></div>
</div>
</div>
<div style="color: #222222; font-family: arial, sans-serif; font-size: 13px; background-color: #ffffff;">
<div>
<div>
<div><a href="http://www.facebook.com/officialpage"><span style="font-size: 10pt;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">Facebook.com/Nicole Moudaber</span></span></span></a></div>
<div><a href="http://www.twitter.com/nicolemoudaber"><span style="font-size: 10pt;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">Twitter.com/NicoleMoudaber</span></span></span></a></div>
<div><span style="font-size: 10pt;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><a href="http://Instagram.com/NicoleMoudaber">Instagram.com/NicoleMoudaber</a><b>&nbsp;</b></span></span></span></div>
<div style="text-align: justify;"><a href="http://soundcloud.com/nicolemoudaber"><span style="font-size: 10pt;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">Soundcloud.com/NicoleMoudaber</span></span></span></a></div>
<div style="text-align: justify;"><span style="font-size: 10pt;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><a href="http://www.nicolemoudaber.com">www.NicoleMoudaber.com</a></span></span></span></div>
</div>
<div><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;"><br /></span></span></div>
<div dir="ltr" style="line-height: 1.15; text-align: center; margin-bottom: 0pt; margin-top: 0pt;"><span style="font-size: 10pt;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">&nbsp;###</span></span></span></div>
<p><span style="font-family: arial, helvetica, sans-serif;"><span style="font-size: 10pt;"><br style="text-align: center;" /> </span> </span></p>
<div dir="ltr" style="line-height: 1.15; margin-bottom: 0pt; margin-top: 0pt;"><span style="font-size: 10pt;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">For all media inquiries, please contact:</span></span></span></div>
<div dir="ltr" style="line-height: 1.15; margin-bottom: 0pt; margin-top: 0pt;"><span style="font-size: 10pt;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">Betty Kang |&nbsp;<a href="mailto:betty@plexipr.com" target="_blank" style="color: #1155cc;">betty@plexipr.com</a></span></span></span></div>
<div dir="ltr" style="line-height: 1.15; margin-bottom: 0pt; margin-top: 0pt;"><span style="line-height: 1.15;"><span style="font-size: 10pt;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">Dance Local. Think Global.</span></span></span></span></div>
<div dir="ltr" style="line-height: 1.15; margin-bottom: 0pt; margin-top: 0pt;"><span style="font-size: 10pt;"><span style="font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">&nbsp;</span></span></span></div>
</div>
</div>
</div>
</div>
<p></body><br />
</html></p>
