---
title: Plexi PR
description: Dance Local. Think Global.
timezone: America/New_York
collections:
  press:
    title: Press Releases
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: press
  values:
    layout: post
    permalink: "/press/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
