---
title: Plexi PR
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  press:
    title: Press Releases
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: press
  values:
    layout: post
    permalink: "/press/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
description: Dance Local. Think Global.
permalink: pretty
google_analytics: UA-134499-3
